import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: 'ltr' | 'rtl';
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.searchPlaceholder': 'Search products, styles, categories...',
    'nav.trackOrder': 'Track Order',
    'nav.wishlist': 'Wishlist',
    'nav.cart': 'Cart',
    'nav.allCategories': 'All Categories',
    'nav.adminLogin': 'Admin Dashboard',
    'hero.shopNow': 'DISCOVER COLLECTION',
    'hero.viewDetails': 'EXPLORE',
    'category.all': 'All Products',
    'product.new': 'NEW',
    'product.sale': 'SALE',
    'product.bestseller': 'BEST SELLER',
    'product.featured': 'FEATURED',
    'product.addToCart': 'Add to Cart',
    'product.selectSize': 'Select Size',
    'product.selectColor': 'Select Color',
    'product.outOfStock': 'Out of Stock',
    'product.inStock': 'In Stock',
    'product.sku': 'SKU',
    'product.description': 'Description',
    'cart.title': 'Your Shopping Bag',
    'cart.empty': 'Your bag is empty.',
    'cart.subtotal': 'Subtotal',
    'cart.shippingNote': 'Shipping & discounts calculated at checkout',
    'cart.checkout': 'Proceed to Checkout',
    'cart.freeShippingProgress': 'Add {amount} more for FREE shipping!',
    'cart.freeShippingEarned': '🎉 You unlocked FREE Shipping!',
    'cart.couponPlaceholder': 'Discount coupon code',
    'cart.applyCoupon': 'Apply',
    'cart.couponApplied': 'Coupon Applied!',
    'checkout.title': 'Express Checkout',
    'checkout.fullName': 'Full Name',
    'checkout.primaryPhone': 'Primary Phone Number',
    'checkout.secondaryPhone': 'Secondary Phone (Optional)',
    'checkout.country': 'Country',
    'checkout.governorate': 'Governorate / State',
    'checkout.address': 'Full Address (Street, Building, Flat)',
    'checkout.selectGovernorate': 'Select your governorate...',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Items Subtotal',
    'checkout.shipping': 'Shipping Cost',
    'checkout.discount': 'Discount',
    'checkout.total': 'Final Total',
    'checkout.placeOrder': 'Confirm Order',
    'checkout.placingOrder': 'Processing...',
    'checkout.successTitle': 'Order Placed Successfully!',
    'checkout.orderNumber': 'Order Reference #',
    'checkout.successMsg': 'Thank you for shopping with ZYRO. Your order details have been saved.',
    'checkout.whatsappConfirm': 'Send WhatsApp Confirmation',
    'checkout.continueShopping': 'Continue Shopping',
    'tracking.title': 'Track Your Order',
    'tracking.subtitle': 'Enter your Order Reference Number or Phone Number',
    'tracking.placeholder': 'e.g. ZYRO-82910 or +2010...',
    'tracking.search': 'Find Order',
    'tracking.noOrder': 'No order found matching this reference.',
    'tracking.status': 'Status',
    'footer.rights': 'All rights reserved. ZYRO Luxury Fashion House.',
    'footer.customerCare': 'Customer Care',
    'footer.shippingPolicy': 'Shipping & Returns',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.socialHeader': 'Follow Us On Social Media',
    'admin.title': 'ZYRO Admin Control Panel',
    'admin.headerTag': 'ADMIN PANEL',
    'admin.loginTitle': 'Admin Sign In',
    'admin.username': 'Username',
    'admin.password': 'Password',
    'admin.loginBtn': 'Access Control Panel',
    'admin.logout': 'Sign Out',
    'admin.tabOverview': 'Overview',
    'admin.tabProducts': 'Products',
    'admin.tabCategories': 'Categories',
    'admin.tabCoupons': 'Coupons',
    'admin.tabAnnouncement': 'Announcement Bar',
    'admin.tabShipping': 'Shipping Rates',
    'admin.tabSocial': 'Social Media',
    'admin.tabOrders': 'Orders',
    'admin.tabBanners': 'Banners',
    'admin.tabReels': 'Video Reels',
    
    // Overview
    'admin.overviewTitle': 'Dashboard Analytics',
    'admin.overviewSubtitle': 'Live summary of ZYRO store operations',
    'admin.totalRevenue': 'Total Revenue',
    'admin.totalOrders': 'Total Orders',
    'admin.activeProducts': 'Active Products',
    'admin.activeCoupons': 'Active Coupons',
    'admin.recentOrders': 'Recent Customer Orders',
    
    // Table Headers & General UI
    'admin.orderRef': 'Order Ref',
    'admin.customer': 'Customer',
    'admin.governorate': 'Governorate',
    'admin.total': 'Total',
    'admin.status': 'Status',
    'admin.actions': 'Actions',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.active': 'Active',
    'admin.hidden': 'Hidden',
    'admin.enabled': 'Enabled',
    'admin.disabled': 'Disabled',
    
    // Products
    'admin.productsTitle': 'Products Management',
    'admin.productsSubtitle': 'Add, edit, manage stock, prices, colors, and sizes',
    'admin.addProduct': 'Add New Product',
    'admin.editProduct': 'Edit Product',
    'admin.productImages': 'Product Images',
    'admin.coverImageNote': 'First image is the main cover',
    'admin.addImage': 'Add Image',
    'admin.productName': 'Product Name',
    'admin.productCategory': 'Product Category',
    'admin.productPrices': 'Prices & Discount ($)',
    'admin.originalPrice': 'Original Price',
    'admin.salePrice': 'Sale Price',
    'admin.productStockSku': 'Stock & SKU Code',
    'admin.stockQty': 'Stock Quantity',
    'admin.productSizes': 'Available Sizes',
    'admin.productColors': 'Color Options & Color-Image Mapping',
    'admin.colorName': 'Color Name',
    'admin.addColor': 'Add Color Option',
    'admin.productDesc': 'Product Description',
    'admin.badgeLabel': 'Product Badge',
    'admin.saveProduct': 'Save Product',
    
    // Categories
    'admin.categoriesTitle': 'Categories',
    'admin.categoriesSubtitle': 'Manage store categories, slugs, order, and visibility',
    'admin.addCategory': 'Create Category',
    'admin.editCategory': 'Manage Category',
    'admin.categoryName': 'Category Name',
    'admin.slug': 'Slug',
    'admin.displayOrder': 'Display Order',
    'admin.visible': 'Visible',
    'admin.show': 'Show',
    'admin.hide': 'Hide',
    'admin.saveCategory': 'Save Category',
    
    // Coupons
    'admin.couponsTitle': 'Discount Codes',
    'admin.couponsSubtitle': 'Set percentages or fixed discounts, usage limits, and expiration dates',
    'admin.addCoupon': 'Create Coupon',
    'admin.editCoupon': 'Edit Discount Code',
    'admin.couponCode': 'Coupon Code',
    'admin.discountType': 'Discount Type',
    'admin.percentage': 'Percentage (%)',
    'admin.fixedAmount': 'Fixed Amount ($)',
    'admin.discountValue': 'Value',
    'admin.expirationDate': 'Expiration Date',
    'admin.usageLimit': 'Usage Limit',
    'admin.usableCheckout': 'Active & Usable at Checkout',
    'admin.saveCoupon': 'Save Discount Code',
    
    // Announcement & Settings
    'admin.announcementTitle': 'Welcome & Announcement Bar Settings',
    'admin.enableAnnouncement': 'Enable Top Announcement Bar',
    'admin.announcementMessage': 'Announcement Message',
    'admin.freeShippingThreshold': 'Free Shipping Order Threshold ($)',
    'admin.saveAnnouncement': 'Save Announcement & Threshold',
    'admin.settingsSaved': 'Settings updated successfully!',
    
    // Shipping
    'admin.shippingTitle': 'Shipping Settings',
    'admin.shippingSubtitle': 'Add countries, governorates/states, and custom shipping prices',
    'admin.addShipping': 'Add Governorate / State',
    'admin.editShipping': 'Manage Shipping Governorate',
    'admin.country': 'Country',
    'admin.governorateName': 'Governorate / State Name',
    'admin.shippingPrice': 'Shipping Price ($)',
    'admin.saveShipping': 'Save Shipping Location',
    
    // Social
    'admin.socialTitle': 'Social Media Links',
    'admin.socialSubtitle': 'Icons automatically appear in the website footer.',
    'admin.facebookUrl': 'Facebook URL',
    'admin.instagramUrl': 'Instagram URL',
    'admin.tiktokUrl': 'TikTok URL',
    'admin.whatsappNum': 'WhatsApp Phone Number (with country code, no +)',
    'admin.youtubeUrl': 'YouTube URL',
    'admin.twitterUrl': 'X (Twitter) URL',
    'admin.saveSocial': 'Save Social Links',
    
    // Orders
    'admin.ordersTitle': 'Orders Management',
    'admin.ordersSubtitle': 'View customer orders, update statuses, print invoices, and send WhatsApp messages',
    'admin.customerInfo': 'Customer Info',
    'admin.deliveryAddress': 'Delivery Address',
    'admin.paymentSummary': 'Payment Summary',
    'admin.orderedItems': 'Ordered Items',
    'admin.invoice': 'Invoice',
    'admin.statusPending': 'Pending',
    'admin.statusProcessing': 'Processing',
    'admin.statusShipped': 'Shipped',
    'admin.statusDelivered': 'Delivered',
    'admin.statusCancelled': 'Cancelled',
    
    // Banners
    'admin.bannersTitle': 'Banners Management',
    'admin.bannersSubtitle': 'Multiple banners in the same position automatically display as a sliding carousel',
    'admin.addBanner': 'Add Banner',
    'admin.editBanner': 'Edit Banner',
    'admin.bannerImage': 'Banner Image (Upload or Direct URL)',
    'admin.bannerTitle': 'Banner Title',
    'admin.bannerSubtitle': 'Banner Subtitle (Optional)',
    'admin.bannerPosition': 'Banner Position',
    'admin.heroPosition': 'Hero Main Slider',
    'admin.midPagePosition': 'Mid Page Section',
    'admin.bottomPagePosition': 'Bottom Page Banner',
    'admin.categoryTopPosition': 'Category Header Banner',
    'admin.targetUrl': 'Click Link / Target URL (Optional)',
    'admin.visibleWebsite': 'Active & Visible on Website',
    'admin.saveBanner': 'Save Banner',
    
    // Reels
    'admin.reelsTitle': 'Video Reels',
    'admin.reelsSubtitle': 'Upload short videos to appear in Instagram/TikTok style carousel',
    'admin.addReel': 'Add Video Reel',
    'admin.editReel': 'Edit Video Reel',
    'admin.reelVideoFile': 'Reels Video File (Upload or Direct URL)',
    'admin.reelThumbnail': 'Poster Thumbnail Image (Optional)',
    'admin.reelTitle': 'Reel Title',
    'admin.visibleReels': 'Active & Visible in Reels Carousel',
    'admin.saveReel': 'Save Video Reel',
    
    // Modals & Invoice
    'admin.confirmDeleteProduct': 'Confirm Delete Product',
    'admin.confirmDeleteOrder': 'Confirm Delete Order',
    'admin.actionUndone': 'Action cannot be undone',
    'admin.confirmDelete': 'Confirm Delete',
    'admin.officialInvoice': 'Official Purchase Invoice',
    'admin.customerDetails': 'Customer Details',
    'admin.item': 'Item',
    'admin.qty': 'Qty',
    'admin.subtotalCost': 'Subtotal',
    'admin.shippingCost': 'Shipping Cost',
    'admin.discountAmount': 'Discount',
    'admin.totalPaid': 'Total Paid',
    'admin.printPdf': 'Print / Save PDF',
  },
  ar: {
    'nav.searchPlaceholder': 'ابحث عن منتج، تصميم، أو فئة...',
    'nav.trackOrder': 'تتبع طلبي',
    'nav.wishlist': 'المفضلة',
    'nav.cart': 'حقيبة التسوق',
    'nav.allCategories': 'جميع الفئات',
    'nav.adminLogin': 'لوحة التحكم',
    'hero.shopNow': 'تسوق التشكيلة الآن',
    'hero.viewDetails': 'استكشف',
    'category.all': 'جميع المنتجات',
    'product.new': 'جديد',
    'product.sale': 'تخفيض',
    'product.bestseller': 'الأكثر مبيعاً',
    'product.featured': 'مميز',
    'product.addToCart': 'إضافة للحقيبة',
    'product.selectSize': 'اختر المقاس',
    'product.selectColor': 'اختر اللون',
    'product.outOfStock': 'نفذت الكمية',
    'product.inStock': 'متوفر بالمخزون',
    'product.sku': 'رمز المنتج (SKU)',
    'product.description': 'الوصف التفصيلي',
    'cart.title': 'حقيبة التسوق الخاصة بك',
    'cart.empty': 'حقيبة التسوق فارغة حالياً.',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shippingNote': 'تُحسب تكاليف الشحن والخصومات عند إتمام الطلب',
    'cart.checkout': 'متابعة إلى الشراء',
    'cart.freeShippingProgress': 'أضف بقيمة {amount} للحصول على شحن مجاني!',
    'cart.freeShippingEarned': '🎉 تهانينا! حصلت على شحن مجاني!',
    'cart.couponPlaceholder': 'رمز كود الخصم',
    'cart.applyCoupon': 'تطبيق',
    'cart.couponApplied': 'تم تطبيق الخصم!',
    'checkout.title': 'إتمام الشراء السريع',
    'checkout.fullName': 'الاسم بالكامل',
    'checkout.primaryPhone': 'رقم الهاتف الرئيسي',
    'checkout.secondaryPhone': 'رقم هاتف إضافي (اختياري)',
    'checkout.country': 'الدولة',
    'checkout.governorate': 'المحافظة / المنطقة',
    'checkout.address': 'العنوان التفصيلي (الشارع، العمارة، الشقة)',
    'checkout.selectGovernorate': 'اختر المحافظة...',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.subtotal': 'مجموع المنتجات',
    'checkout.shipping': 'تكلفة الشحن',
    'checkout.discount': 'قيمة الخصم',
    'checkout.total': 'المبلغ الإجمالي النهائي',
    'checkout.placeOrder': 'تأكيد وإرسال الطلب',
    'checkout.placingOrder': 'جاري إرسال الطلب...',
    'checkout.successTitle': 'تم إرسال طلبك بنجاح!',
    'checkout.orderNumber': 'رقم مرجع الطلب #',
    'checkout.successMsg': 'شكراً لتسوقك من زيرو. تم حفظ بيانات طلبك بنجاح وسيتواصل معك فريقنا قريباً.',
    'checkout.whatsappConfirm': 'إرسال تأكيد عبر واتساب',
    'checkout.continueShopping': 'متابعة التسوق',
    'tracking.title': 'تتبع حالة طلبك',
    'tracking.subtitle': 'أدخل رقم مرجع الطلب أو رقم الهاتف المسجل',
    'tracking.placeholder': 'مثال: ZYRO-82910 أو 010...',
    'tracking.search': 'البحث عن الطلب',
    'tracking.noOrder': 'لم نتمكن من العثور على طلب بهذا الرقم.',
    'tracking.status': 'حالة الطلب',
    'footer.rights': 'جميع الحقوق محفوظة. دار أزياء زيرو ZYRO.',
    'footer.customerCare': 'العناية بالعملاء',
    'footer.shippingPolicy': 'الشحن والاسترجاع',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.terms': 'الشروط والأحكام',
    'footer.socialHeader': 'تابعنا على وسائل التواصل الاجتماعي',
    'admin.title': 'لوحة إشراف وإدارة زيرو ZYRO',
    'admin.headerTag': 'لوحة التحكم',
    'admin.loginTitle': 'تسجيل دخول الإدارة',
    'admin.username': 'اسم المستخدم',
    'admin.password': 'كلمة المرور',
    'admin.loginBtn': 'دخول لوحة التحكم',
    'admin.logout': 'تسجيل الخروج',
    'admin.tabOverview': 'نظرة عامة',
    'admin.tabProducts': 'المنتجات',
    'admin.tabCategories': 'الأقسام',
    'admin.tabCoupons': 'كوبونات الخصم',
    'admin.tabAnnouncement': 'شريط الإعلانات',
    'admin.tabShipping': 'أسعار الشحن',
    'admin.tabSocial': 'التواصل الاجتماعي',
    'admin.tabOrders': 'إدارة الطلبات',
    'admin.tabBanners': 'البنرات الإعلانية',
    'admin.tabReels': 'فيديوهات الريلز',
    
    // Overview
    'admin.overviewTitle': 'تحليلات لوحة التحكم',
    'admin.overviewSubtitle': 'ملخص مباشر لعمليات وإحصائيات متجر زيرو',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.totalOrders': 'إجمالي الطلبات',
    'admin.activeProducts': 'المنتجات النشطة',
    'admin.activeCoupons': 'الكوبونات النشطة',
    'admin.recentOrders': 'أحدث طلبات العملاء',
    
    // Table Headers & General UI
    'admin.orderRef': 'مرجع الطلب',
    'admin.customer': 'العميل',
    'admin.governorate': 'المحافظة',
    'admin.total': 'الإجمالي',
    'admin.status': 'الحالة',
    'admin.actions': 'الإجراءات',
    'admin.edit': 'تعديل',
    'admin.delete': 'حذف',
    'admin.save': 'حفظ',
    'admin.cancel': 'إلغاء',
    'admin.active': 'نشط',
    'admin.hidden': 'مخفي',
    'admin.enabled': 'مفعل',
    'admin.disabled': 'معطل',
    
    // Products
    'admin.productsTitle': 'إدارة المنتجات',
    'admin.productsSubtitle': 'إضافة، تعديل، وإدارة المخزون، الأسعار، الألوان، والمقاسات',
    'admin.addProduct': 'إضافة منتج جديد',
    'admin.editProduct': 'تعديل المنتج',
    'admin.productImages': 'صور المنتج',
    'admin.coverImageNote': 'الصورة الأولى هي صورة الغلاف الرئيسية',
    'admin.addImage': 'إضافة صورة',
    'admin.productName': 'اسم المنتج',
    'admin.productCategory': 'قسم المنتج',
    'admin.productPrices': 'الأسعار والخصم ($)',
    'admin.originalPrice': 'السعر الأصلي',
    'admin.salePrice': 'سعر الخصم',
    'admin.productStockSku': 'الكميات ورمز المنتج (SKU)',
    'admin.stockQty': 'الكمية بالمخزون',
    'admin.productSizes': 'المقاسات المتاحة',
    'admin.productColors': 'خيارات الألوان وربط الصور',
    'admin.colorName': 'اسم اللون',
    'admin.addColor': 'إضافة لون جديد',
    'admin.productDesc': 'وصف المنتج',
    'admin.badgeLabel': 'شارة المنتج',
    'admin.saveProduct': 'حفظ المنتج',
    
    // Categories
    'admin.categoriesTitle': 'الأقسام والترتيب',
    'admin.categoriesSubtitle': 'إدارة أقسام المتجر، الروابط، الترتيب، والإظهار',
    'admin.addCategory': 'إضافة قسم جديد',
    'admin.editCategory': 'إدارة القسم',
    'admin.categoryName': 'اسم القسم',
    'admin.slug': 'الرمز (Slug)',
    'admin.displayOrder': 'ترتيب العرض',
    'admin.visible': 'الحالة',
    'admin.show': 'إظهار',
    'admin.hide': 'إخفاء',
    'admin.saveCategory': 'حفظ القسم',
    
    // Coupons
    'admin.couponsTitle': 'كوبونات الخصم',
    'admin.couponsSubtitle': 'إعداد نسبة الخصم أو المبالغ الثابتة وحدود الاستخدام وتاريخ الانتهاء',
    'admin.addCoupon': 'إضافة كود خصم',
    'admin.editCoupon': 'تعديل كود الخصم',
    'admin.couponCode': 'كود الخصم',
    'admin.discountType': 'نوع الخصم',
    'admin.percentage': 'نسبة مئوية (%)',
    'admin.fixedAmount': 'مبلغ ثابت ($)',
    'admin.discountValue': 'قيمة الخصم',
    'admin.expirationDate': 'تاريخ الانتهاء',
    'admin.usageLimit': 'حد الاستخدام',
    'admin.usableCheckout': 'نشط ومتاح للاستخدام عند الشراء',
    'admin.saveCoupon': 'حفظ كود الخصم',
    
    // Announcement & Settings
    'admin.announcementTitle': 'إعدادات شريط الإعلانات العلوية',
    'admin.enableAnnouncement': 'تفعيل شريط الإعلانات العلوي',
    'admin.announcementMessage': 'نص الإعلان',
    'admin.freeShippingThreshold': 'الحد الأدنى للشحن المجاني ($)',
    'admin.saveAnnouncement': 'حفظ الإعلان والحد الأدنى',
    'admin.settingsSaved': 'تم تحديث الإعدادات بنجاح!',
    
    // Shipping
    'admin.shippingTitle': 'إعدادات الشحن والمحافظات',
    'admin.shippingSubtitle': 'إضافة الدول، المحافظات/المناطق، وأسعار الشحن المخصصة',
    'admin.addShipping': 'إضافة محافظة / منطقة',
    'admin.editShipping': 'إدارة منطقة الشحن',
    'admin.country': 'الدولة',
    'admin.governorateName': 'اسم المحافظة / المنطقة',
    'admin.shippingPrice': 'سعر الشحن ($)',
    'admin.saveShipping': 'حفظ منطقة الشحن',
    
    // Social
    'admin.socialTitle': 'روابط التواصل الاجتماعي',
    'admin.socialSubtitle': 'تظهر الأيقونات تلقائياً في أسفل صفحات الموقع.',
    'admin.facebookUrl': 'رابط فيسبوك',
    'admin.instagramUrl': 'رابط انستغرام',
    'admin.tiktokUrl': 'رابط تيك توك',
    'admin.whatsappNum': 'رقم الواتساب (بالرمز الدولي بدون +)',
    'admin.youtubeUrl': 'رابط يوتيوب',
    'admin.twitterUrl': 'رابط X (تويتر)',
    'admin.saveSocial': 'حفظ روابط التواصل',
    
    // Orders
    'admin.ordersTitle': 'إدارة الطلبات',
    'admin.ordersSubtitle': 'مراجعة طلبات العملاء، تحديث الحالات، طباعة الفواتير، وإرسال رسائل واتساب',
    'admin.customerInfo': 'بيانات العميل',
    'admin.deliveryAddress': 'عنوان التوصيل',
    'admin.paymentSummary': 'ملخص الدفع',
    'admin.orderedItems': 'المنتجات المطلوبة',
    'admin.invoice': 'الفاتورة',
    'admin.statusPending': 'معلق',
    'admin.statusProcessing': 'جاري المعالجة',
    'admin.statusShipped': 'تم الشحن',
    'admin.statusDelivered': 'تم التوصيل',
    'admin.statusCancelled': 'ملغي',
    
    // Banners
    'admin.bannersTitle': 'البنرات الإعلانية',
    'admin.bannersSubtitle': 'البنرات المتعددة في نفس الموضع تظهر تلقائياً كمعرض متحرك',
    'admin.addBanner': 'إضافة بنر',
    'admin.editBanner': 'تعديل البنر',
    'admin.bannerImage': 'صورة البنر (رفع أو رابط مباشر)',
    'admin.bannerTitle': 'عنوان البنر',
    'admin.bannerSubtitle': 'العنوان الفرعي (اختياري)',
    'admin.bannerPosition': 'موضع البنر',
    'admin.heroPosition': 'المعرض الرئيسي (الهيرو)',
    'admin.midPagePosition': 'منتصف الصفحة',
    'admin.bottomPagePosition': 'أسفل الصفحة',
    'admin.categoryTopPosition': 'أعلى صفحات الأقسام',
    'admin.targetUrl': 'رابط التوجيه / الانقال (اختياري)',
    'admin.visibleWebsite': 'نشط وظاهر على الموقع',
    'admin.saveBanner': 'حفظ البنر',
    
    // Reels
    'admin.reelsTitle': 'فيديوهات الريلز',
    'admin.reelsSubtitle': 'رفع فيديوهات قصيرة لتظهر أسلوب انستغرام وتيك توك',
    'admin.addReel': 'إضافة فيديو ريلز',
    'admin.editReel': 'تعديل فيديو الريلز',
    'admin.reelVideoFile': 'ملف فيديو الريلز (رفع أو رابط مباشر)',
    'admin.reelThumbnail': 'صورة الغلاف المؤقتة (اختياري)',
    'admin.reelTitle': 'عنوان الفيديو',
    'admin.visibleReels': 'نشط وظاهر في معرض الريلز',
    'admin.saveReel': 'حفظ فيديو الريلز',
    
    // Modals & Invoice
    'admin.confirmDeleteProduct': 'تأكيد حذف المنتج',
    'admin.confirmDeleteOrder': 'تأكيد حذف الطلب',
    'admin.actionUndone': 'لا يمكن التراجع عن هذا الإجراء',
    'admin.confirmDelete': 'تأكيد الحذف',
    'admin.officialInvoice': 'فاتورة شراء رسمية',
    'admin.customerDetails': 'تفاصيل العميل',
    'admin.item': 'المنتج',
    'admin.qty': 'الكمية',
    'admin.subtotalCost': 'المجموع الفرعي',
    'admin.shippingCost': 'تكلفة الشحن',
    'admin.discountAmount': 'قيمة الخصم',
    'admin.totalPaid': 'المبلغ المدفوع النهائي',
    'admin.printPdf': 'طباعة / حفظ PDF',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('zyro_lang');
    return (saved === 'ar' || saved === 'en') ? saved : 'ar'; // Default to Arabic or user preference
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('zyro_lang', lang);
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  const t = (key: string, fallback?: string): string => {
    return translations[language][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
